name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Build Docker image
        run: |
          docker build -t dartly/vania:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push dartly/vania:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest Docker image
            docker pull dartly/vania:latest
            
            # Create a docker-compose.yml file
            echo "
            version: '3.9'
            services:
              vania:
                image: dartly/vania:latest
                container_name: vania
                restart: always
                volumes:
                  - app:/app
                  - ./public:/public
                  - ./storage:/storage
                ports:
                  - '8000:8000'
            volumes:
              app:
            " > docker-compose.yml
            
            # Deploy using docker-compose
            docker-compose down || true      # Stop and remove existing containers
            docker-compose up -d             # Start new containers in detached mode
