name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t dartly/vania:latest -t dartly/vania:${IMAGE_TAG} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker images
        run: |
          docker push dartly/vania:latest
          docker push dartly/vania:${{ github.sha }}

      - name: Save docker-compose.yml
        run: |
          echo "version: '3.8'" > docker-compose.yml
          echo "services:" >> docker-compose.yml
          echo "  vania:" >> docker-compose.yml
          echo "    image: dartly/vania:latest" >> docker-compose.yml
          echo "    ports:" >> docker-compose.yml
          echo "      - '8000:8000'" >> docker-compose.yml
          echo "    volumes:" >> docker-compose.yml
          echo "      - app:/app" >> docker-compose.yml
          echo "      - /path/to/public:/public" >> docker-compose.yml
          echo "      - /path/to/storage:/storage" >> docker-compose.yml
          echo "volumes:" >> docker-compose.yml
          echo "  app:" >> docker-compose.yml
          
      - name: Upload docker-compose.yml
        uses: actions/upload-artifact@v2
        with:
          name: docker-compose
          path: docker-compose.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download docker-compose.yml
        uses: actions/download-artifact@v2
        with:
          name: docker-compose

      - name: SSH to server and deploy Docker Compose
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest Docker image
            docker pull dartly/vania:latest
            docker-compose -f docker-compose.yml down || true
            docker-compose -f docker-compose.yml up -d
