name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Build Docker image
        run: |
          # 使用当前 Git 提交的 SHA 作为标签
          IMAGE_TAG=${{ github.sha }}
          docker build -t dartly/vania:latest -t dartly/vania:${IMAGE_TAG} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker images
        run: |
          # 推送最新镜像和带 SHA 标签的镜像
          docker push dartly/vania:latest
          docker push dartly/vania:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to server and pull Docker image
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest Docker image
            docker pull dartly/vania:latest
            docker stop vania || true         # Stop the running container if it exists
            docker rm vania || true           # Remove the container if it exists
            docker run -d -p 8000:8000 \
              -v app:/app \
              -v /path/to/public:/public \
              -v /path/to/storage:/storage \
              --name vania dartly/vania:latest  # Run the new container with volume mappings
