name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Build Docker image
        run: |
          docker build -t dartly/vania:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push dartly/vania:latest

      - name: Check if docker-compose.yml exists
        run: |
          if [ -f "./docker-compose.yml" ]; then
            echo "docker-compose.yml exists."
          else
            echo "docker-compose.yml does not exist."
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Debug Secrets
        run: |
          echo "SERVER_IP: ${{ secrets.SERVER_IP }}"
          echo "SERVER_USER: ${{ secrets.SERVER_USER }}"

      - name: SCP to server
        uses: appleboy/scp-action@v0.1.0  # 请检查最新版本
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "/"
          port: 22
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          rm: false
          debug: true  # 启用调试模式

      - name: SSH to server and restart Docker container
        uses: appleboy/ssh-action@v0.1.0  # 请检查最新版本
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /  # 进入目标目录
            docker-compose pull  # 拉取最新的镜像
            docker-compose up -d  # 启动容器
